### ISSUE TITLE
Magenta colours in colors.h misnamed

### ISSUE THREAD

**Issue by 2Tie** [johannes-fetz/joengine#2]
Using jo_clear_background() with JO_COLOR_Magenta, JO_COLOR_SemiMagenta, JO_COLOR_MediumMagenta, or JO_COLOR_DarkMagenta all result in Cyan shades rather than the expected Magenta. 

If could suggest a fix, just rename the Magentas to Cyans, since Purple is already close to expected Magenta.

**Comment by johannes-fetz** [comment]
fixed in master
