### ISSUE TITLE
Input Sampling Timing

### ISSUE THREAD

**Issue by ponut64** [johannes-fetz/joengine#20]
With Jo's built-in input sampling functions, the inputs are sampled within the frame (between vblank).

However, in order to properly sample inputs on Saturn, you should check for them in time with vblank.

This problem sometimes causes inputs to be dropped, because the state change of input was false when checked. We checked for it within the frame but its period of being pressed or not passed on the next vblank, so we missed the key being pressed (if it was only checked or held for 1 frame).

**Comment by johannes-fetz** [comment]
Fixed
