### ISSUE TITLE
Samples No Longer Compile

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#22]
I have pulled the latest joengine trunk. When I try to compile any of the Samples they no longer work. I am on Linux. 

make: execvp: ../../Compiler/LINUX/bin/sh-none-elf-gcc-8.2.0: Permission denied
../../Compiler/COMMON/jo_engine_makefile:294: recipe for target 'main.o' failed
make: *** [main.o] Error 127
make: *** Waiting for unfinished jobs....
../../Compiler/COMMON/jo_engine_makefile:294: recipe for target 'sonic.o' failed
make: *** [sonic.o] Error 127

Steps to repro:
1)  git clone https://github.com/johannes-fetz/joengine.git
2) cd to Samples/demo - Sonic
3) ./compile

**Comment by johannes-fetz** [comment]
Use chmod to change rights on files. I will fix this asap

**Comment by johannes-fetz** [comment]
Fixed
