### ISSUE TITLE
2nd Multitap Support is Broken

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#23]
Hi Johannes, 

Players 1-6 are working with "static __jo_force_inline bool jo_is_input_key_down(const int port,  const jo_gamepad_keys) however players 7-12 are broken. 

These work:
jo_is_input_key_down(0, JO_KEY_LEFT)) // player 1
jo_is_input_key_down(1, JO_KEY_LEFT)) // player 2
jo_is_input_key_down(2, JO_KEY_LEFT)) // player 3
jo_is_input_key_down(3, JO_KEY_LEFT)) // player 4
jo_is_input_key_down(4, JO_KEY_LEFT)) // player 5
jo_is_input_key_down(5, JO_KEY_LEFT)) // player 6

These do not work:
jo_is_input_key_down(6, JO_KEY_LEFT)) // player 7
jo_is_input_key_down(7, JO_KEY_LEFT)) // player 8
jo_is_input_key_down(8, JO_KEY_LEFT)) // player 9
jo_is_input_key_down(9, JO_KEY_LEFT)) // player 10
jo_is_input_key_down(10, JO_KEY_LEFT)) // player 11
jo_is_input_key_down(11, JO_KEY_LEFT)) // player 12

The fix is to add 9 to the port number if the port >= 6. 

Fix:
#define SECOND_MULTITAP_OFFSET 9
jo_is_input_key_down(6 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 7
jo_is_input_key_down(7 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 8
jo_is_input_key_down(8 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 9
jo_is_input_key_down(9 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 10
jo_is_input_key_down(10 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 11
jo_is_input_key_down(11 +  SECOND_MULTITAP_OFFSET, JO_KEY_LEFT)) // player 12

I've glanced at input.h and input.c and there are a lot of functions that need to be fixed. Basically any function that takes in a "const int port" needs to have this fix implemented. I prototyped a fix for jo_is_input_available() as follows:

`#define SECOND_MULTITAP_OFFSET 9
static  __jo_force_inline bool	jo_is_input_available(const int port)
{
	int adjustedPort = port;

	if(adjustedPort >= 6)
	{
		adjustedPort += SECOND_MULTITAP_OFFSET;
	}

#if JO_COMPILE_USING_SGL
    return (Smpc_Peripheral[adjustedPort].id != PER_ID_NotConnect);
#else
    return (jo_inputs[adjustedPort].id != PER_ID_NotConnect);
#endif
}
`

**Comment by johannes-fetz** [comment]
Fixed
