### ISSUE TITLE
How to Handle ABC+Start Key Press?

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#27]
Hi Johannes, 

I want to catch the ABC+Start key press such that it exits back out to the title screen. Currently when player 1 hits ABC+Start the game freezes. I tried adding an input callback but it looks like the game freezes before it gets there. 

How can I handle ABC+Start key press? Thanks in advance.

**Comment by johannes-fetz** [comment]
Hi, I will add something in the engine

**Comment by johannes-fetz** [comment]
Fixed. I added jo_core_set_restart_game_callback() where you can pass your function

**Comment by slinga-homebrew** [comment]
Thanks, I verified it works.
