### ISSUE TITLE
Trunk Doesn't Build in Release

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#29]
I updated to trunk just now, debug builds compile (JO_DEBUG = 1) but release builds (JO_DEBUG = 1) fail to compile. 

Here is the compiler error:

`
../jo_engine/vdp2_malloc.o
../../jo_engine/vdp2_malloc.c: In function 'jo_vdp2_malloc':
../../jo_engine/vdp2_malloc.c:164:13: warning: implicit declaration of function 'jo_core_error'; did you mean 'jo_core_tv_on'? [-Wimplicit-function-declaration]
             jo_core_error("Out of VDP2 memory");
             ^~~~~~~~~~~~~
             jo_core_tv_on
`

**Comment by johannes-fetz** [comment]
Damn
