### ISSUE TITLE
jo_sprite_set_palette() Doesn't Work in JO_480p Mode

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#32]
I'll stop annoying you now, just wanted to file another bug report. 

For my next project I want to use palette swaps for my characters and use 480i mode. "demo - hardcoded image" sets a palette for an 8bit sprite. When compiled for standard resolution the demo works. When I added "JO_480p = 1" to the makefile the 8 bit image still displays, but it is no longer using the palette. 

Is this an issue with Jo Engine or with SGL?

**Comment by johannes-fetz** [comment]
Neither. This mode is still in developement. Don't use it :)
