### ISSUE TITLE
Enabling VDP2 planes corrupts jo_printf memory

### ISSUE THREAD

**Issue by retrohead** [johannes-fetz/joengine#55]
I'm not 100% sure what is happening here but after enabling VDP2 planes, the palette used by jo_printf seems to get corrupted but this is not present in the sample

**Comment by johannes-fetz** [comment]
When you change VDP2 layer settings, it's not safe to use jo_printf anymore.
You have to register your own font and draw it on the appropriate layer. like the "NBG2 font" sample.
Then you can use jo_nbg2_printf() for example instead of jo_printf() with the same usage.
