### ISSUE TITLE
8bit Demo Questions

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#57]
Hi Johannes, 

I'm trying to understand the 8bit TGA demo. What tool did you use to create the TGA? I am trying with GIMP and it's creating 256 color indexes. Is it possible to use 8bpp and have transparencies?

66  	// Load a 8 bits ▲ 255 colors (MAX) NOT 256 or it will glitch! ▲ TGA
67  	// Instead of JO_COLOR_Transparent, you can pass an index on your palette
68  	jo_sprite_add_tga("TEX", "SON8.TGA", JO_COLOR_Transparent);

**Comment by johannes-fetz** [comment]
Hi,

I'm using [IrfanView ](https://www.irfanview.com/):

![how](https://user-images.githubusercontent.com/34853793/110510423-76073180-8103-11eb-8f8c-7808c0da2d9d.png)

And yes, you can select the index int the palette that should be transparent (0 to 255).
Just replace JO_COLOR_Transparent by a number like 42 and see

**Comment by slinga-homebrew** [comment]
Thanks, i will try Irfan Viewer.
