### ISSUE TITLE
NBG3, NBG0 do not seem to be accessible

### ISSUE THREAD

**Issue by retrohead** [johannes-fetz/joengine#59]
I have tried many things to access NBG0 and NBG3, using the line scroll demo I changed it to jo_vdp2_set_nbg3_8bits_image and changed the make file to disable printf. This worked but when I enable other screens, I am getting corruption.

I would like to simply change the colour of another background other than NBG1 for now, is there an alternative function I can use?

**Comment by retrohead** [comment]
oops, it would help if I enabled the background first

**Comment by johannes-fetz** [comment]
Hi, I need a sample that show the problem.

**Comment by johannes-fetz** [comment]
Yes:
    - When NBG0 is set as 2048 or 32768 colors, NBG2 can not longer be displayed.
    - When NBG0 is set at 16,770,000 colors, NBG1 to NBG3 can not longer be displayed.
    - When NBG1 is set at 2048 or 32768 colors, NBG3 can longer be displayed.
