### ISSUE TITLE
Feature Request: sprPolyLine

### ISSUE THREAD

**Issue by slinga-homebrew** [johannes-fetz/joengine#68]
Hi Johannes, 

Hope all is well. In ```jo_3d```. in the ```void jo_3d_set_mesh_polygon_color(jo_3d_mesh * const mesh, const jo_color color, const unsigned int index)``` function is hardcoded to always use ```sprPolygon```. I would like the ability to use ```sprPolyLine``` as well. Thanks in advance.

**Comment by johannes-fetz** [comment]
I added two new functions:
void                        jo_3d_set_mesh_polygon_wireframe(jo_3d_mesh * const mesh, const unsigned int index, bool wireframe);
void                                jo_3d_set_mesh_polygon_color_ex(jo_3d_mesh * const mesh, const jo_color color, const unsigned int index, bool wireframe);

**Comment by slinga-homebrew** [comment]
Thank you!
